### ISSUE TITLE
doc bug : executing tests in the ~/tempest-upstream/tempest dir fail

### ISSUE THREAD

**Issue by pinikomarov** [itzikb/docker-tempest#19]
Hi :), found a doc bug : 
executing tests in the ~/tempest-upstream/tempest dir itself fails.
*any other dir is ok ..
tested it a couple of times : 
stacktrace and reproducer is here:
http://pastebin.test.redhat.com/786074

I'm suggesting the  docs should say : 
$ cd ~/tempest-upstream/tempest
$ sudo ~/scripts/run_tempest.sh
$ source ../bin/activate
$ stestr list
$ cd ../ 
$python -m testtools.run tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_list_hosts
*the last one is a simple list hosts test run and it will make sure the users can test the tempest setup out of the box

**Comment by itzikb** [comment]
Hi,
Thanks for the issue!
I updated python-tempestconf and now it should work as documented.
